version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.4
    working_directory: /go/src/github.com/Go-Forensics/BinaryTransforms
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
        file: ./coverage.txt